version: '3.8'

services:
  integraite-backend:
    build: .
    container_name: integraite-backend-container
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - integraite-network

networks:
  integraite-network:
    driver: bridge
